### ISSUE TITLE
unexplained issue when unattended

### ISSUE THREAD

**Issue by on-three** [on-three/weeabot#22]
2014-09-17 10:50:08-0700 [WeeaBot,client] #/jp/shows : .c cable
2014-09-17 16:31:09-0700 [WeeaBot,client] connection lost
2014-09-17 16:31:21-0700 [-] Stopping factory <__main__.WeeaBotFactory instance at 0xff68c50c>
2014-09-17 16:31:21-0700 [-] Main loop terminated.
2014-09-17 16:31:21-0700 [-] Unhandled error in Deferred:
2014-09-17 16:31:21-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 298, in connectionLost
            protocol.connectionLost(reason)
          File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 213, in connectionLost
            self.factory._disconnectedDeferred.callback(None)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/onthree/code/weeabot/weeabot/whatson.py", line 74, in __call__
            self._callback_handler(response, self._tv_channel, self._irc_channel, self._user, self._url, self._next)
          File "/home/onthree/code/weeabot/weeabot/whatson.py", line 162, in on_Whatson_response
            program = scrape_tv_schedule(response, tv_channel)
          File "/home/onthree/code/weeabot/weeabot/terebi_ookoku.py", line 92, in scrape_tv_schedule
            content_block = soup('dl', {'class' : 'basicTxt'})[0]
        exceptions.IndexError: list index out of range

Aborted (core dumped)

**Comment by on-three** [comment]
has not happened for quite a while.
resolving
