### ISSUE TITLE
Unicode/UTF-8 Decoding or Encoding Error in Whatson Plugin

### ISSUE THREAD

**Issue by on-three** [on-three/weeabot#42]
Encoding issues in .w (whatson) since moved to windows native.

            return codecs.utf_8_decode(input, errors, True)
        exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in po
sition 7: invalid start byte

2015-03-17 20:54:28-0800 [HTTPPageGetter,client] Unhandled error in Deferred:
2015-03-17 20:54:28-0800 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 299
, in connectionLost
            protocol.connectionLost(reason)
          File "C:\Python27\lib\site-packages\twisted\web\client.py", line 213,
in connectionLost
            self.factory._disconnectedDeferred.callback(None)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 3
83, in callback
            self._startRunCallbacks(result)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 4
91, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 5
78, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "C:\Users\onthree\code\weeabot\weeabot\translator.py", line 47, i
n __call__
            self._callback(response, self._text, **self._kwargs)
          File "C:\Users\onthree\code\weeabot\weeabot\whatson.py", line 201, in
on_translation
            date=ustrftime(program.start_time, u'%m/%d (%a)'), \
          File "C:\Users\onthree\code\weeabot\weeabot\whatson.py", line 50, in u
strftime
            return t.strftime(format.encode('utf-8')).decode('utf-8')
          File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
            return codecs.utf_8_decode(input, errors, True)
        exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in po
sition 7: invalid start byte

2015-03-17 20:54:28-0800 [HTTPPageGetter,client] #/jp/shows-->♥01,00 ·?··☼ ♥01,0
0 ·?·?·<??·? ☼ ♥01,00 enchou ☼ ♥01,00 head of a place designated with the suffix
 -en (e.g. kindergarten principal, director of a zoo, etc.) ☼
2015-03-17 20:54:28-0800 [HTTPPageGetter,client] #/jp/shows-->♥01,00 ???·☼ ♥01,0
0 ·?·?·<??·? ☼ ♥01,00 enchou ☼ ♥01,00 1: extension; elongation; prolongation; le
ngthening; 2: (Noun) Enchou era (923.4.11-931.4.26) ☼
2015-03-17 20:54:29-0800 [HTTPPageGetter,client] #/jp/shows-->♥01,00 ·?·? ☼ ♥01,
00 ·?·?·<??·? ☼ ♥01,00 enchou ☼ ♥01,00 dome; cupola ☼
2015-03-17 20:54:29-0800 [HTTPPageGetter,client] Stopping factory <HTTPClientFac
tory: http://jisho.org/words?jap=entyou&eng=&dict=edict>
2015-03-17 20:55:44-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarhiphop.com/videos/video.php?v=wshhsrAt53xLFWKV093t
Playing: http://www.worldstarhiphop.com/videos/video.php?v=wshhsrAt53xLFWKV093t
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
AV: 00:00:53 / 00:00:53 (99%) A-V:  0.000 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 20:58:26-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarhiphop.com/videos/video.php?v=wshh7g6848CT6KGL5P4H
Playing: http://www.worldstarhiphop.com/videos/video.php?v=wshh7g6848CT6KGL5P4H
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 406x720 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
AV: 00:01:01 / 00:01:01 (99%) A-V:  0.000 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:04:36-0800 [WeeaBot,client] Starting factory <HTTPClientFactory: h
ttp://tv.so-net.ne.jp/past/40066014044.action>
2015-03-17 21:04:37-0800 [HTTPPageGetter,client] C:\Python27\lib\site-packages\r
equests\packages\urllib3\util\ssl_.py:79: requests.packages.urllib3.exceptions.I
nsecurePlatformWarning: A true SSLContext object is not available. This prevents
 urllib3 from configuring SSL appropriately and may cause certain SSL connection
s to fail. For more information, see https://urllib3.readthedocs.org/en/latest/s
ecurity.html#insecureplatformwarning.
2015-03-17 21:04:37-0800 [HTTPPageGetter,client] Starting factory <HTTPClientFac
tory: http://api.microsofttranslator.com/V2/Ajax.svc/Translate?text=%5BHV%5D%E5%
B1%B1%E6%9D%91%E7%BE%8E%E7%B4%97%E3%82%B5%E3%82%B9%E3%83%9A%E3%83%B3%E3%82%B9+%E
4%B8%8D%E5%80%AB%E8%AA%BF%E6%9F%BB%E5%93%A1+%E7%89%87%E5%B1%B1%E7%94%B1%E7%BE%8E
%EF%BC%98&from=ja&to=en>
2015-03-17 21:04:37-0800 [HTTPPageGetter,client] Stopping factory <HTTPClientFac
tory: http://tv.so-net.ne.jp/past/40066014044.action>
2015-03-17 21:04:37-0800 [HTTPPageGetter,client] on_translation: ??[HV] Yamamura
 MISA suspense infidelity investigator Katayama Yumiko 8"
2015-03-17 21:04:37-0800 [HTTPPageGetter,client] Stopping factory <HTTPClientFac
tory: http://api.microsofttranslator.com/V2/Ajax.svc/Translate?text=%5BHV%5D%E5%
B1%B1%E6%9D%91%E7%BE%8E%E7%B4%97%E3%82%B5%E3%82%B9%E3%83%9A%E3%83%B3%E3%82%B9+%E
4%B8%8D%E5%80%AB%E8%AA%BF%E6%9F%BB%E5%93%A1+%E7%89%87%E5%B1%B1%E7%94%B1%E7%BE%8E
%EF%BC%98&from=ja&to=en>
2015-03-17 21:05:08-0800 [WeeaBot,client] #/jp/shows : .c vpara
2015-03-17 21:05:08-0800 [WeeaBot,client] "c:/Program Files (x86)/AutoHotkey/Aut
oHotkey.exe" c:/Users/onthree/code/weeabot/autohotkey/command.ahk 292
2015-03-17 21:05:27-0800 [WeeaBot,client] #/jp/shows : .c mondo
2015-03-17 21:05:27-0800 [WeeaBot,client] "c:/Program Files (x86)/AutoHotkey/Aut
oHotkey.exe" c:/Users/onthree/code/weeabot/autohotkey/command.ahk 554
2015-03-17 21:06:27-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarcandy.com/candy/53539
Playing: http://www.worldstarcandy.com/candy/53539
[ytdl_hook] ERROR: Unsupported URL: http://www.worldstarcandy.com/candy/53539
[ytdl_hook] youtube-dl failed, trying to play URL directly ...
Failed to recognize file format.

Exiting... (Errors when loading file)
2015-03-17 21:08:16-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarhiphop.com/featured/79007
Playing: http://www.worldstarhiphop.com/featured/79007
[ytdl_hook] ERROR: Unsupported URL: http://www.worldstarhiphop.com/featured/7900
7
[ytdl_hook] youtube-dl failed, trying to play URL directly ...
Failed to recognize file format.

Exiting... (Errors when loading file)
2015-03-17 21:08:34-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 https://vimeo.com/41821601
Playing: https://vimeo.com/41821601
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 640x480 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
AV: 00:00:33 / 00:00:33 (99%) A-V:  0.000 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:09:14-0800 [WeeaBot,client] <unicode instance at 0x4a466f0 with st
r error:
         Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\python\reflect.py", line 4
43, in safe_str
            return str(o)
        UnicodeEncodeError: 'ascii' codec can't encode characters in position 37
-38: ordinal not in range(128)
        >
2015-03-17 21:09:14-0800 [WeeaBot,client] mpv.exe --ontop --no-border -autofit=6
40x480 --geometry 600:120 http://a.pomf.se/djqnzl.webm
Playing: http://a.pomf.se/djqnzl.webm
 (+) Video --vid=1 (vp8)
 (+) Audio --aid=1 (*) (vorbis)
File tags:
 Title: ayy lmao-OZ1-yNTWXj4
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 853x480 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
AV: 00:00:21 / 00:00:21 (99%) A-V:  0.000 Dropped: 0/3 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:09:39-0800 [WeeaBot,client] URL IS: http://a.pomf.se/cudhes.webm
2015-03-17 21:09:39-0800 [WeeaBot,client] mpv.exe --ontop --no-border -autofit=6
40x480 --geometry 600:120 http://a.pomf.se/cudhes.webm
Playing: http://a.pomf.se/cudhes.webm
 (+) Audio --aid=1 (*) (vorbis)
AO: [wasapi] 48000Hz stereo 2ch float
A: 00:00:34 / 00:00:34 (99%) Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:12:06-0800 [WeeaBot,client] URL IS: http://a.pomf.se/anjxum.jpg
2015-03-17 21:12:06-0800 [WeeaBot,client] mpv.exe --ontop --no-border -autofit=6
40x480 --geometry 600:120 http://a.pomf.se/anjxum.jpg
Playing: http://a.pomf.se/anjxum.jpg
2015-03-17 21:12:30-0800 [WeeaBot,client] #/jp/shows : .c mute
2015-03-17 21:12:30-0800 [WeeaBot,client] "c:/Program Files (x86)/AutoHotkey/Aut
oHotkey.exe" c:/Users/onthree/code/weeabot/autohotkey/command.ahk \!m
2015-03-17 21:12:35-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarhiphop.com/videos/video.php?v=wshhPxEmq52F7O6Fgty5
Playing: http://www.worldstarhiphop.com/videos/video.php?v=wshhPxEmq52F7O6Fgty5
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
Failed to open http://a.pomf.se/anjxum.jpg.ache: 10s+51689KB

Exiting... (Errors when loading file)
AV: 00:06:12 / 00:06:12 (99%) A-V:  0.000 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:18:52-0800 [-] mpv.exe --ontop --no-border --geometry=1280x720+600
+120 http://www.worldstarhiphop.com/videos/video.php?v=wshh1eLox0c6NZ0j0VdA
Playing: http://www.worldstarhiphop.com/videos/video.php?v=wshh1eLox0c6NZ0j0VdA
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
AV: 00:03:11 / 00:03:11 (99%) A-V:  0.000 Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:34:02-0800 [WeeaBot,client] URL IS: http://8ch.net/pol/src/1426656
078940.jpg
2015-03-17 21:34:02-0800 [WeeaBot,client] mpv.exe --ontop --no-border -autofit=6
40x480 --geometry 600:120 http://8ch.net/pol/src/1426656078940.jpg
Playing: http://8ch.net/pol/src/1426656078940.jpg
 (+) Video --vid=1 (mjpeg)
VO: [opengl] 500x326 yuv420p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
V: 00:00:00 / 00:00:01 (0%) Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 21:49:50-0800 [WeeaBot,client] URL IS: http://i.huffpost.com/gen/1824
160/images/o-CAT-PEOPLE-DOG-PEOPLE-facebook.jpg
2015-03-17 21:49:51-0800 [WeeaBot,client] mpv.exe --ontop --no-border -autofit=6
40x480 --geometry 600:120 http://i.huffpost.com/gen/1824160/images/o-CAT-PEOPLE-
DOG-PEOPLE-facebook.jpg
Playing: http://i.huffpost.com/gen/1824160/images/o-CAT-PEOPLE-DOG-PEOPLE-facebo
ok.jpg
 (+) Video --vid=1 (mjpeg)
VO: [opengl] 2000x1000 yuv444p
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
[osd/libass] No usable fontconfig configuration file found, using fallback.
V: 00:00:00 / 00:00:01 (0%) Cache:  0s+0KB

Exiting... (End of file)
2015-03-17 22:20:46-0800 [WeeaBot,client] #/jp/shows : .c mute
2015-03-17 22:20:46-0800 [WeeaBot,client] "c:/Program Files (x86)/AutoHotkey/Aut
oHotkey.exe" c:/Users/onthree/code/weeabot/autohotkey/command.ahk \!m
2015-03-17 22:24:07-0800 [WeeaBot,client] #/jp/shows : .c entame
2015-03-17 22:24:07-0800 [WeeaBot,client] "c:/Program Files (x86)/AutoHotkey/Aut
oHotkey.exe" c:/Users/onthree/code/weeabot/autohotkey/command.ahk 559
2015-03-17 22:24:35-0800 [WeeaBot,client] Starting factory <HTTPClientFactory: h
ttp://tv.so-net.ne.jp/past/40066915244.action>
2015-03-17 22:24:35-0800 [HTTPPageGetter,client] Unhandled error in Deferred:
2015-03-17 22:24:35-0800 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 299
, in connectionLost
            protocol.connectionLost(reason)
          File "C:\Python27\lib\site-packages\twisted\web\client.py", line 213,
in connectionLost
            self.factory._disconnectedDeferred.callback(None)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 3
83, in callback
            self._startRunCallbacks(result)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 4
91, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 5
78, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "C:\Users\onthree\code\weeabot\weeabot\translator.py", line 47, i
n __call__
            self._callback(response, self._text, **self._kwargs)
          File "C:\Users\onthree\code\weeabot\weeabot\whatson.py", line 201, in
on_translation
            date=ustrftime(program.start_time, u'%m/%d (%a)'), \
          File "C:\Users\onthree\code\weeabot\weeabot\whatson.py", line 50, in u
strftime
            return t.strftime(format.encode('utf-8')).decode('utf-8')
          File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
            return codecs.utf_8_decode(input, errors, True)
        exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in po
sition 7: invalid start byte

2015-03-17 22:24:35-0800 [HTTPPageGetter,client] C:\Python27\lib\site-packages\r
equests\packages\urllib3\util\ssl_.py:79: requests.packages.urllib3.exceptions.I
nsecurePlatformWarning: A true SSLContext object is not available. This prevents
 urllib3 from configuring SSL appropriately and may cause certain SSL connection
s to fail. For more information, see https://urllib3.readthedocs.org/en/latest/s
ecurity.html#insecureplatformwarning.
2015-03-17 22:24:36-0800 [HTTPPageGetter,client] Starting factory <HTTPClientFac
tory: http://api.microsofttranslator.com/V2/Ajax.svc/Translate?text=%5BHV%5D%5B%
E5%AD%97%5D%E3%81%9D%E3%82%8C%E3%81%84%E3%81%91%EF%BC%81%E3%82%A2%E3%83%B3%E3%83
%91%E3%83%B3%E3%83%9E%E3%83%B3+%23422&from=ja&to=en>
2015-03-17 22:24:36-0800 [HTTPPageGetter,client] Stopping factory <HTTPClientFac
tory: http://tv.so-net.ne.jp/past/40066915244.action>
2015-03-17 22:24:36-0800 [HTTPPageGetter,client] on_translation: ??[HV] [S] it d
on't! Anpanman #422"
2015-03-17 22:24:36-0800 [HTTPPageGetter,client] Stopping factory <HTTPClientFac
tory: http://api.microsofttranslator.com/V2/Ajax.svc/Translate?text=%5BHV%5D%5B%
E5%AD%97%5D%E3%81%9D%E3%82%8C%E3%81%84%E3%81%91%EF%BC%81%E3%82%A2%E3%83%B3%E3%83
%91%E3%83%B3%E3%83%9E%E3%83%B3+%23422&from=ja&to=en>

**Comment by on-three** [comment]
Fixed by bfad0ea21c04395e40ca5457fbc12b4430cb6557

**Comment by on-three** [comment]
Not fixed.
Takes time (a failed page response?) to bring this out.
